import { AuthenticatedLayout } from "@/components/layout/authenticated-layout";
import { Header } from "@/components/layout/header";
import { ProfileDropdown } from "@/components/header/profile-dropdown";
import { Search } from "@/components/header/search";
import { ThemeSwitch } from "@/components/theme-switch";
import { SidebarNav } from "@/app/(dashboard)/_components/settings/sidebar-nav";
import { Main } from "@/components/layout/main";
import { Separator } from "@/components/ui/separator";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function SettingsLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <AuthenticatedLayout fixed>
                <Header>
                    <Search />
                    <div className="ml-auto flex items-center space-x-4">
                        <ThemeSwitch />
                        <ProfileDropdown />
                    </div>
                </Header>
                <Main fixed>
                    <div className="space-y-0.5">
                        <h1 className="text-2xl font-bold tracking-tight md:text-3xl">
                            Settings
                        </h1>
                        <p className="text-muted-foreground">
                            Manage your account settings and set e-mail preferences.
                        </p>
                    </div>
                    <Separator className="my-4 lg:my-6" />
                    <div className="flex flex-1 flex-col space-y-2 overflow-hidden md:space-y-2 lg:flex-row lg:space-y-0 lg:space-x-12">
                        <aside className="top-0 lg:sticky lg:w-1/5">
                            <SidebarNav />
                        </aside>
                        <div className="flex w-full overflow-y-hidden p-1">
                            {children}
                        </div>
                    </div>
                </Main>
            </AuthenticatedLayout>
        </>
    );
};