import { AuthenticatedLayout } from "@/components/layout/authenticated-layout";
import { Header } from "@/components/layout/header";
import { ProfileDropdown } from "@/components/header/profile-dropdown";
import { Search } from "@/components/header/search";
import { ThemeSwitch } from "@/components/theme-switch";

import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function UsersLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <AuthenticatedLayout>
                <Header fixed>
                    <Search />
                    <div className="ml-auto flex items-center space-x-4">
                        <ThemeSwitch />
                        <ProfileDropdown />
                    </div>
                </Header>
                {children}
            </AuthenticatedLayout>
        </>
    );
};